-- MySQL Script generated by MySQL Workbench
-- Пн 17 сен 2018 23:19:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baddb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `baddb` ;

-- -----------------------------------------------------
-- Schema baddb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baddb` DEFAULT CHARACTER SET cp1250 ;
USE `baddb` ;

-- -----------------------------------------------------
-- Table `baddb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baddb`.`comment` ;

CREATE TABLE IF NOT EXISTS `baddb`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baddb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baddb`.`user` ;

CREATE TABLE IF NOT EXISTS `baddb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(40) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_comment_idx` (`comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_comment`
    FOREIGN KEY (`comment_id`)
    REFERENCES `baddb`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baddb`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `baddb`.`article` ;

CREATE TABLE IF NOT EXISTS `baddb`.`article` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `content` VARCHAR(45) NULL,
  `comment_id` INT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_comment1_idx` (`comment_id` ASC) VISIBLE,
  INDEX `fk_article_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_article_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `baddb`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `baddb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
